docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    - run:
        name: Sync DB and Files from master if we are not on master
        command: |
          if [[ "$LAGOON_GIT_BRANCH" != "master" ]]; then
            # Only if we don't have a database yet
            if tables=$(drush sqlq 'show tables;') && [ -z "$tables" ]; then
                drush sql-sync @lagoon.master @self
                drush rsync @lagoon.master:%files @self:%files -- --omit-dir-times --no-perms --no-group --no-owner --chmod=ugo=rwX
            fi
          fi
        service: cli
    - run:
        name: env variables
        command: env
        service: cli
    - run:
        name: drush cim
        command: drush -y cim
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli



environments:
  master:
    cronjobs:
      - name: drush cron
        schedule: "H * * * *" # this will run the cron once per hour
        command: drush cron
        service: cli
    # routes:
    #   - varnish:
    #       - "domain.com"
